import type { Metadata } from "next";
import Link from "next/link";

import { PageHeading } from "@/components/ui/page-heading";
import { getDocumentsPageData } from "@/features/documents/queries";

export const metadata: Metadata = { title: "Documents" };

export default async function DocumentsPage({ searchParams }: PageProps<"/app/documents">) {
  const { q = "" } = await searchParams; const data=await getDocumentsPageData(typeof q==="string"?q:"");
  return <div><PageHeading title="Documents" description={`Draft and issued business records for ${data.context.workspace.name}.`} action={<Link href="/app/documents/new" className="inline-flex min-h-11 items-center rounded-lg bg-civ-blue px-5 text-sm font-semibold text-white">Create Draft</Link>}/><form className="mt-8 flex gap-2"><input aria-label="Search documents" name="q" defaultValue={typeof q==="string"?q:""} className="min-h-11 min-w-0 flex-1 rounded-lg border border-border bg-surface px-3 text-sm text-text" placeholder="Search number, draft reference or customer"/><button className="min-h-11 rounded-lg border border-border px-4 text-sm font-semibold text-text">Search</button></form>
    {data.documents.length?<div className="mt-4 overflow-x-auto rounded-xl border border-border bg-surface"><table className="w-full min-w-[54rem] text-left text-sm"><thead className="bg-surface-muted text-muted"><tr><th className="px-4 py-3">Document</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Customer</th><th className="px-4 py-3">Creator / issuer</th><th className="px-4 py-3">Total</th><th className="px-4 py-3">Date</th></tr></thead><tbody className="divide-y divide-border">{data.documents.map(d=><tr key={d.id}><td className="px-4 py-4"><Link className="font-semibold text-link" href={`/app/documents/${d.id}`}>{d.documentNumber??d.draftReference}</Link></td><td className="px-4 py-4"><span className="font-semibold text-text">{d.status === "ISSUED" ? "Issued" : "Draft"}</span></td><td className="px-4 py-4 text-text">{d.type.replaceAll("_"," ")}</td><td className="px-4 py-4 text-text">{d.customer?.name??"—"}</td><td className="px-4 py-4 text-muted">{(d.status === "ISSUED" ? d.issuedBy : d.createdBy)?.name||(d.status === "ISSUED" ? d.issuedBy : d.createdBy)?.email||"Member"}</td><td className="px-4 py-4 font-semibold text-text">{d.currency} {d.grandTotal.toFixed(2)}</td><td className="px-4 py-4 text-muted">{(d.issuedAt??d.draftDate).toLocaleDateString("en-GH")}</td></tr>)}</tbody></table></div>:<div className="mt-6 rounded-xl border border-dashed border-border p-12 text-center"><h2 className="font-bold text-text">No documents yet</h2><p className="mt-2 text-sm text-muted">Create a draft without consuming document allowance or credits.</p></div>}</div>;
}
