export const CIV_PLAN_CATALOG = [
  {
    code: "FREE",
    name: "Free",
    description: "CIV essentials for an individual workspace.",
    memberLimit: 1,
    documentLimit: 50,
    betaPrice: "0.0000",
    monthlyPrice: "0.0000",
    currency: "GHS",
    billingMode: "FREE",
    isActive: true,
    isPublic: true,
    isAvailableForNewWorkspaces: true,
    sortOrder: 10,
    features: { betaAccess: true },
  },
  {
    code: "STARTER",
    name: "Starter",
    description: "A small workspace for getting started with CIV.",
    memberLimit: 3,
    documentLimit: 500,
    betaPrice: "0.0000",
    monthlyPrice: "50.0000",
    currency: "GHS",
    billingMode: "RECURRING",
    isActive: true,
    isPublic: true,
    isAvailableForNewWorkspaces: true,
    sortOrder: 20,
    features: { betaAccess: true },
  },
  {
    code: "BUSINESS",
    name: "Business",
    description: "A growing business workspace with a larger team allowance.",
    memberLimit: 10,
    documentLimit: 2_000,
    betaPrice: "0.0000",
    monthlyPrice: "100.0000",
    currency: "GHS",
    billingMode: "RECURRING",
    isActive: true,
    isPublic: true,
    isAvailableForNewWorkspaces: true,
    sortOrder: 30,
    features: { betaAccess: true },
  },
  {
    code: "PRO",
    name: "Pro",
    description: "A high-capacity CIV workspace for larger teams.",
    memberLimit: 30,
    documentLimit: 10_000,
    betaPrice: "0.0000",
    monthlyPrice: "200.0000",
    currency: "GHS",
    billingMode: "RECURRING",
    isActive: true,
    isPublic: true,
    isAvailableForNewWorkspaces: true,
    sortOrder: 40,
    features: { betaAccess: true },
  },
  {
    code: "ENTERPRISE",
    name: "Enterprise",
    description: "Custom CIV pricing and limits for enterprise workspaces.",
    memberLimit: null,
    documentLimit: null,
    betaPrice: "0.0000",
    monthlyPrice: "0.0000",
    currency: "GHS",
    billingMode: "CUSTOM",
    isActive: true,
    isPublic: true,
    isAvailableForNewWorkspaces: false,
    sortOrder: 50,
    features: { betaAccess: true, customLimits: true },
  },
] as const;

export const CIV_DOCUMENT_CREDIT_PACK_CATALOG = [
  {
    code: "CREDITS_100",
    name: "100 Document Credits",
    description: "A small carry-forward document credit pack.",
    creditAmount: 100,
    price: "30.0000",
    currency: "GHS",
    isActive: true,
    isPublic: true,
    sortOrder: 10,
  },
  {
    code: "CREDITS_500",
    name: "500 Document Credits",
    description: "Carry-forward capacity for growing document needs.",
    creditAmount: 500,
    price: "125.0000",
    currency: "GHS",
    isActive: true,
    isPublic: true,
    sortOrder: 20,
  },
  {
    code: "CREDITS_1000",
    name: "1,000 Document Credits",
    description: "A larger carry-forward document credit pack.",
    creditAmount: 1_000,
    price: "200.0000",
    currency: "GHS",
    isActive: true,
    isPublic: true,
    sortOrder: 30,
  },
  {
    code: "CREDITS_5000",
    name: "5,000 Document Credits",
    description: "High-capacity carry-forward document credits.",
    creditAmount: 5_000,
    price: "750.0000",
    currency: "GHS",
    isActive: true,
    isPublic: true,
    sortOrder: 40,
  },
] as const;

export const CIV_DEFAULT_TRIAL_CONFIGURATION = {
  enabled: true,
  trialPlanCode: "BUSINESS",
  durationDays: 14,
  fallbackPlanCode: "FREE",
  newWorkspacesOnly: true,
  oneTrialPerWorkspace: true,
  paymentMethodRequired: false,
  allowManualGrant: true,
} as const;
