import type { PlatformRole } from "@/generated/prisma/enums";

export const PLATFORM_CAPABILITIES = {
  VIEW_PLATFORM_DASHBOARD: "VIEW_PLATFORM_DASHBOARD",
  VIEW_PLATFORM_ANALYTICS: "VIEW_PLATFORM_ANALYTICS",
  VIEW_USERS: "VIEW_USERS",
  VIEW_WORKSPACES: "VIEW_WORKSPACES",
  VIEW_PLANS: "VIEW_PLANS",
  VIEW_STORAGE_ANALYTICS: "VIEW_STORAGE_ANALYTICS",
  VIEW_PLATFORM_ACTIVITY: "VIEW_PLATFORM_ACTIVITY",
  VIEW_AUTH_ANALYTICS: "VIEW_AUTH_ANALYTICS",
  MANAGE_PLATFORM_TEAM: "MANAGE_PLATFORM_TEAM",
  MANAGE_PLATFORM_SETTINGS: "MANAGE_PLATFORM_SETTINGS",
  VIEW_FINANCIAL_ANALYTICS: "VIEW_FINANCIAL_ANALYTICS",
  VIEW_PAYMENTS: "VIEW_PAYMENTS",
  MANAGE_PAYMENT_REFUNDS: "MANAGE_PAYMENT_REFUNDS",
  RECONCILE_PAYMENTS: "RECONCILE_PAYMENTS",
  MANAGE_PLATFORM_PLANS: "MANAGE_PLATFORM_PLANS",
  VIEW_TRIALS: "VIEW_TRIALS",
  MANAGE_TRIALS: "MANAGE_TRIALS",
  VIEW_SYSTEM_HEALTH: "VIEW_SYSTEM_HEALTH",
} as const;

export type PlatformCapability =
  (typeof PLATFORM_CAPABILITIES)[keyof typeof PLATFORM_CAPABILITIES];

export const ALL_PLATFORM_CAPABILITIES = Object.freeze(
  Object.values(PLATFORM_CAPABILITIES),
) as readonly PlatformCapability[];

const platformRoleCapabilities = {
  PLATFORM_OWNER: ALL_PLATFORM_CAPABILITIES,
  PLATFORM_ADMIN: [
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_DASHBOARD,
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_USERS,
    PLATFORM_CAPABILITIES.VIEW_WORKSPACES,
    PLATFORM_CAPABILITIES.VIEW_PLANS,
    PLATFORM_CAPABILITIES.VIEW_STORAGE_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_ACTIVITY,
    PLATFORM_CAPABILITIES.VIEW_AUTH_ANALYTICS,
    PLATFORM_CAPABILITIES.MANAGE_PLATFORM_TEAM,
    PLATFORM_CAPABILITIES.MANAGE_PLATFORM_SETTINGS,
    PLATFORM_CAPABILITIES.VIEW_SYSTEM_HEALTH,
    PLATFORM_CAPABILITIES.VIEW_TRIALS,
    PLATFORM_CAPABILITIES.MANAGE_TRIALS,
    PLATFORM_CAPABILITIES.VIEW_PAYMENTS,
    PLATFORM_CAPABILITIES.MANAGE_PAYMENT_REFUNDS,
    PLATFORM_CAPABILITIES.RECONCILE_PAYMENTS,
  ],
  ANALYST: [
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_DASHBOARD,
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_PLANS,
    PLATFORM_CAPABILITIES.VIEW_STORAGE_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_ACTIVITY,
    PLATFORM_CAPABILITIES.VIEW_AUTH_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_TRIALS,
    PLATFORM_CAPABILITIES.VIEW_PAYMENTS,
  ],
  SUPPORT: [
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_DASHBOARD,
    PLATFORM_CAPABILITIES.VIEW_USERS,
    PLATFORM_CAPABILITIES.VIEW_WORKSPACES,
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_ACTIVITY,
    PLATFORM_CAPABILITIES.VIEW_TRIALS,
  ],
  FINANCE: [
    PLATFORM_CAPABILITIES.VIEW_PLATFORM_DASHBOARD,
    PLATFORM_CAPABILITIES.VIEW_PLANS,
    PLATFORM_CAPABILITIES.VIEW_FINANCIAL_ANALYTICS,
    PLATFORM_CAPABILITIES.VIEW_TRIALS,
    PLATFORM_CAPABILITIES.VIEW_PAYMENTS,
    PLATFORM_CAPABILITIES.RECONCILE_PAYMENTS,
  ],
} as const satisfies Record<PlatformRole, readonly PlatformCapability[]>;

export function getPlatformCapabilitiesForRole(
  role: PlatformRole,
): readonly PlatformCapability[] {
  return platformRoleCapabilities[role];
}

export function hasPlatformCapability(
  membership: { role: PlatformRole },
  capability: PlatformCapability,
) {
  return getPlatformCapabilitiesForRole(membership.role).includes(capability);
}
