export const AUDIT_ACTIONS = {
  WORKSPACE_CREATED: "WORKSPACE_CREATED",
  WORKSPACE_UPDATED: "WORKSPACE_UPDATED",
  WORKSPACE_PLAN_CHANGED: "WORKSPACE_PLAN_CHANGED",
  MEMBER_INVITED: "MEMBER_INVITED",
  INVITATION_CANCELLED: "INVITATION_CANCELLED",
  INVITATION_RENEWED: "INVITATION_RENEWED",
  INVITATION_ACCEPTED: "INVITATION_ACCEPTED",
  MEMBER_ROLE_CHANGED: "MEMBER_ROLE_CHANGED",
  MEMBER_SUSPENDED: "MEMBER_SUSPENDED",
  MEMBER_REACTIVATED: "MEMBER_REACTIVATED",
  MEMBER_REMOVED: "MEMBER_REMOVED",
  DOCUMENT_CREATED: "DOCUMENT_CREATED",
  DOCUMENT_ISSUED: "DOCUMENT_ISSUED",
  DOCUMENT_VOIDED: "DOCUMENT_VOIDED",
  DOCUMENT_STATUS_CHANGED: "DOCUMENT_STATUS_CHANGED",
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  ITEM_CREATED: "ITEM_CREATED",
  ITEM_UPDATED: "ITEM_UPDATED",
  RATE_CREATED: "RATE_CREATED",
  RATE_UPDATED: "RATE_UPDATED",
} as const;

export type AuditAction =
  (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_RESOURCE_TYPES = {
  WORKSPACE: "WORKSPACE",
  MEMBERSHIP: "MEMBERSHIP",
  INVITATION: "INVITATION",
  SUBSCRIPTION: "SUBSCRIPTION",
  DOCUMENT: "DOCUMENT",
  CUSTOMER: "CUSTOMER",
  ITEM: "ITEM",
  RATE: "RATE",
} as const;

export type AuditResourceType =
  (typeof AUDIT_RESOURCE_TYPES)[keyof typeof AUDIT_RESOURCE_TYPES];

export const AUDIT_ACTION_RESOURCE = {
  WORKSPACE_CREATED: AUDIT_RESOURCE_TYPES.WORKSPACE,
  WORKSPACE_UPDATED: AUDIT_RESOURCE_TYPES.WORKSPACE,
  WORKSPACE_PLAN_CHANGED: AUDIT_RESOURCE_TYPES.SUBSCRIPTION,
  MEMBER_INVITED: AUDIT_RESOURCE_TYPES.INVITATION,
  INVITATION_CANCELLED: AUDIT_RESOURCE_TYPES.INVITATION,
  INVITATION_RENEWED: AUDIT_RESOURCE_TYPES.INVITATION,
  INVITATION_ACCEPTED: AUDIT_RESOURCE_TYPES.INVITATION,
  MEMBER_ROLE_CHANGED: AUDIT_RESOURCE_TYPES.MEMBERSHIP,
  MEMBER_SUSPENDED: AUDIT_RESOURCE_TYPES.MEMBERSHIP,
  MEMBER_REACTIVATED: AUDIT_RESOURCE_TYPES.MEMBERSHIP,
  MEMBER_REMOVED: AUDIT_RESOURCE_TYPES.MEMBERSHIP,
  DOCUMENT_CREATED: AUDIT_RESOURCE_TYPES.DOCUMENT,
  DOCUMENT_ISSUED: AUDIT_RESOURCE_TYPES.DOCUMENT,
  DOCUMENT_VOIDED: AUDIT_RESOURCE_TYPES.DOCUMENT,
  DOCUMENT_STATUS_CHANGED: AUDIT_RESOURCE_TYPES.DOCUMENT,
  CUSTOMER_CREATED: AUDIT_RESOURCE_TYPES.CUSTOMER,
  CUSTOMER_UPDATED: AUDIT_RESOURCE_TYPES.CUSTOMER,
  ITEM_CREATED: AUDIT_RESOURCE_TYPES.ITEM,
  ITEM_UPDATED: AUDIT_RESOURCE_TYPES.ITEM,
  RATE_CREATED: AUDIT_RESOURCE_TYPES.RATE,
  RATE_UPDATED: AUDIT_RESOURCE_TYPES.RATE,
} as const satisfies Record<AuditAction, AuditResourceType>;

export function isAuditAction(value: string): value is AuditAction {
  return Object.hasOwn(AUDIT_ACTION_RESOURCE, value);
}
