"use client";
import { useActionState, useMemo, useState } from "react";
import Link from "next/link";
import { saveDraftAction, type DraftFormState } from "@/features/documents/actions";

type Line = { catalogItemId: string | null; customRateId: string | null; description: string; quantity: string; unitPrice: string };
type Option = { id: string; name: string };
export function DraftEditor({ documentId, initial, customers, items, rates }: { documentId: string | null; initial: { type: string; customerId: string | null; currency: string; draftDate: string; dueDate: string; notes: string; lines: Line[] }; customers: Option[]; items: Array<Option & { description: string | null; unitPrice: string; currency: string }>; rates: Array<Option & { type: string; value: string }> }) {
  const [state, action, pending] = useActionState(saveDraftAction.bind(null, documentId), {} as DraftFormState); const [lines, setLines] = useState(initial.lines);
  const previewTotal = useMemo(() => lines.reduce((sum,line)=>sum+(Number(line.quantity)||0)*(Number(line.unitPrice)||0),0),[lines]);
  const field="min-h-11 w-full rounded-lg border border-border bg-page px-3 text-sm text-text focus:border-civ-blue focus:outline-none";
  const update=(index:number, patch:Partial<Line>)=>setLines(current=>current.map((line,i)=>i===index?{...line,...patch}:line));
  return <form action={action} className="grid gap-7"><input type="hidden" name="lines" value={JSON.stringify(lines)}/>
    <section className="grid gap-4 rounded-xl border border-border bg-surface p-5 sm:grid-cols-2 sm:p-6"><label className="grid gap-1.5 text-sm font-semibold text-text">Document type<select className={field} name="type" defaultValue={initial.type}><option value="INVOICE">Invoice</option><option value="RECEIPT">Receipt</option><option value="VAT_INVOICE">VAT invoice</option></select></label><label className="grid gap-1.5 text-sm font-semibold text-text">Customer<select className={field} name="customerId" defaultValue={initial.customerId??""}><option value="">No customer selected</option>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold text-text">Draft date<input className={field} type="date" name="draftDate" defaultValue={initial.draftDate} required/></label><label className="grid gap-1.5 text-sm font-semibold text-text">Due date<input className={field} type="date" name="dueDate" defaultValue={initial.dueDate}/></label><label className="grid gap-1.5 text-sm font-semibold text-text">Currency<input className={field} name="currency" defaultValue={initial.currency} maxLength={3} required/></label><label className="grid gap-1.5 text-sm font-semibold text-text sm:col-span-2">Notes<textarea className={`${field} min-h-24 py-3`} name="notes" defaultValue={initial.notes}/></label></section>
    <section aria-labelledby="line-items-title"><div className="flex items-center justify-between gap-3"><div><h2 id="line-items-title" className="text-xl font-bold text-text">Line items</h2><p className="mt-1 text-sm text-muted">Saved totals are recalculated by CIV on the server.</p></div><button type="button" className="min-h-11 rounded-lg border border-civ-blue px-4 text-sm font-semibold text-link" onClick={()=>setLines(current=>[...current,{catalogItemId:null,customRateId:null,description:"",quantity:"1",unitPrice:"0.00"}])}>Add line</button></div>
      <div className="mt-4 grid gap-4">{lines.map((line,index)=><article key={index} className="rounded-xl border border-border bg-surface p-4 sm:p-5"><div className="flex items-center justify-between"><h3 className="font-bold text-text">Line {index+1}</h3><button type="button" disabled={lines.length===1} className="min-h-11 px-3 text-sm font-semibold text-danger disabled:opacity-40" onClick={()=>setLines(current=>current.filter((_,i)=>i!==index))}>Remove</button></div><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="grid gap-1.5 text-sm font-semibold text-text sm:col-span-2">Catalogue entry<select className={field} value={line.catalogItemId??""} onChange={event=>{const item=items.find(i=>i.id===event.target.value);update(index,item?{catalogItemId:item.id,description:item.description||item.name,unitPrice:item.unitPrice}:{catalogItemId:null});}}><option value="">Custom line</option>{items.map(item=><option value={item.id} key={item.id}>{item.name} · {item.currency} {item.unitPrice}</option>)}</select></label><label className="grid gap-1.5 text-sm font-semibold text-text sm:col-span-2">Description<textarea className={`${field} min-h-20 py-3`} value={line.description} onChange={e=>update(index,{description:e.target.value})} required/></label><label className="grid gap-1.5 text-sm font-semibold text-text">Quantity<input className={field} inputMode="decimal" value={line.quantity} onChange={e=>update(index,{quantity:e.target.value})} required/></label><label className="grid gap-1.5 text-sm font-semibold text-text">Unit price<input className={field} inputMode="decimal" value={line.unitPrice} onChange={e=>update(index,{unitPrice:e.target.value})} required/></label><label className="grid gap-1.5 text-sm font-semibold text-text sm:col-span-2">Rate<select className={field} value={line.customRateId??""} onChange={e=>update(index,{customRateId:e.target.value||null})}><option value="">No rate</option>{rates.map(rate=><option value={rate.id} key={rate.id}>{rate.name} · {rate.value}{rate.type==="PERCENTAGE"?"%":" fixed"}</option>)}</select></label></div></article>)}</div>
    </section><section className="flex flex-col gap-4 rounded-xl border border-border bg-surface p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-muted">On-screen estimate before server validation</p><p className="mt-1 text-2xl font-bold text-text">{initial.currency} {previewTotal.toFixed(2)}</p></div><div className="flex flex-wrap gap-2"><Link href="/app/documents" className="min-h-11 rounded-lg border border-border px-4 py-3 text-sm font-semibold text-text">Back</Link><button disabled={pending} className="min-h-11 rounded-lg bg-civ-blue px-5 text-sm font-semibold text-white disabled:opacity-60">{pending?"Saving…":"Save Draft"}</button></div></section>{state.message?<p role="status" className={state.errors?"text-sm text-danger":"text-sm text-success"}>{state.message}</p>:null}
  </form>;
}
