import type { IssuedDocumentSnapshot } from "@/features/documents/snapshots";

const money = (currency: string, value: string) => `${currency} ${value}`;

export function IssuedDocumentView({ snapshot }: { snapshot: IssuedDocumentSnapshot }) {
  return <article className="mt-8 overflow-hidden border border-border bg-surface">
    <header className="border-b border-border p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-civ-blue">{snapshot.document.type.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-bold text-text">{snapshot.document.documentNumber}</h2><p className="mt-1 text-sm text-muted">Issued {new Date(snapshot.document.issuedAt).toLocaleString("en-GH")}</p></div><div className="text-right"><p className="font-bold text-text">{snapshot.issuer.displayName}</p><p className="mt-1 text-sm text-muted">{snapshot.issuer.address || snapshot.issuer.country}</p>{snapshot.issuer.businessTin?<p className="text-sm text-muted">TIN {snapshot.issuer.businessTin}</p>:null}</div></div></header>
    <section className="grid gap-5 border-b border-border p-5 sm:grid-cols-2 sm:p-7"><div><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Customer</h3><p className="mt-2 font-semibold text-text">{snapshot.customer?.name ?? "Walk-in customer"}</p>{snapshot.customer?.address?<p className="mt-1 text-sm text-muted">{snapshot.customer.address}</p>:null}</div><div className="sm:text-right"><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Record</h3><p className="mt-2 text-sm text-text">Issue date: {snapshot.document.issueDate}</p>{snapshot.document.dueDate?<p className="text-sm text-text">Due date: {snapshot.document.dueDate}</p>:null}<p className="text-sm text-text">Issued by: {snapshot.issuedBy.displayName}</p></div></section>
    <div className="overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="bg-surface-muted text-muted"><tr><th className="px-5 py-3">Description</th><th className="px-5 py-3 text-right">Qty</th><th className="px-5 py-3 text-right">Unit price</th><th className="px-5 py-3 text-right">Rate</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-border">{snapshot.lines.map(line=><tr key={line.order}><td className="px-5 py-4 text-text">{line.description}</td><td className="px-5 py-4 text-right text-text">{line.quantity}</td><td className="px-5 py-4 text-right text-text">{money(snapshot.document.currency,line.unitPrice)}</td><td className="px-5 py-4 text-right text-muted">{line.customRate ? money(snapshot.document.currency,line.customRate.amount) : "—"}</td><td className="px-5 py-4 text-right font-semibold text-text">{money(snapshot.document.currency,line.total)}</td></tr>)}</tbody></table></div>
    <section className="grid gap-6 border-t border-border p-5 sm:grid-cols-[1fr_22rem] sm:p-7"><div>{snapshot.document.notes?<><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Notes</h3><p className="mt-2 whitespace-pre-wrap text-sm text-text">{snapshot.document.notes}</p></>:null}</div><dl className="grid gap-2 text-sm"><div className="flex justify-between gap-4"><dt>Subtotal</dt><dd>{money(snapshot.document.currency,snapshot.totals.subtotal)}</dd></div>{snapshot.tax?.components.map(component=><div className="flex justify-between gap-4" key={component.code}><dt>{component.name}</dt><dd>{money(snapshot.document.currency,component.amount)}</dd></div>)}{snapshot.tax?<div className="flex justify-between gap-4 font-semibold"><dt>Taxable value</dt><dd>{money(snapshot.document.currency,snapshot.totals.taxableValue)}</dd></div>:snapshot.totals.customRates !== "0.00"?<div className="flex justify-between gap-4"><dt>Custom rates</dt><dd>{money(snapshot.document.currency,snapshot.totals.customRates)}</dd></div>:null}<div className="mt-2 flex justify-between gap-4 border-t border-border pt-3 text-lg font-bold"><dt>Grand total</dt><dd>{money(snapshot.document.currency,snapshot.totals.grandTotal)}</dd></div></dl></section>
  </article>;
}
