import Link from "next/link";

import { VerificationBarcode } from "@/components/ui/verification-barcode";
import { buildSnapshotAppliedRateRows, formatAppliedRateLabel } from "@/features/documents/applied-rates";
import type { IssuedDocumentSnapshot } from "@/features/documents/snapshots";

const money = (currency: string, value: string) => `${currency} ${value}`;

export function IssuedDocumentView({ snapshot }: { snapshot: IssuedDocumentSnapshot }) {
  const appliedRates = buildSnapshotAppliedRateRows(snapshot);
  const verificationCode = snapshot.verification?.code ?? null;
  return <article className="mt-8 overflow-hidden border border-border bg-surface">
    {snapshot.document.isTestDocument ? <div className="border-b-2 border-danger bg-danger px-5 py-4 text-center text-lg font-black tracking-wide text-white">TEST DOCUMENT — NOT VALID</div> : null}
    <header className="border-b border-border p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-civ-blue">{snapshot.document.type.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-bold text-text">{snapshot.document.documentNumber}</h2><p className="mt-1 text-sm text-muted">Issued {new Date(snapshot.document.issuedAt).toLocaleString("en-GH")}</p></div><div className="text-right"><p className="font-bold text-text">{snapshot.issuer.displayName}</p><p className="mt-1 text-sm text-muted">{snapshot.issuer.address || snapshot.issuer.country}</p>{snapshot.issuer.businessTin?<p className="text-sm text-muted">TIN {snapshot.issuer.businessTin}</p>:null}</div></div></header>
    <section className="grid gap-5 border-b border-border p-5 sm:grid-cols-2 sm:p-7"><div><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Customer</h3><p className="mt-2 font-semibold text-text">{snapshot.customer?.name ?? "Walk-in customer"}</p>{snapshot.customer?.address?<p className="mt-1 text-sm text-muted">{snapshot.customer.address}</p>:null}</div><div className="sm:text-right"><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Record</h3><p className="mt-2 text-sm text-text">Issue date: {snapshot.document.issueDate}</p>{snapshot.document.dueDate?<p className="text-sm text-text">Due date: {snapshot.document.dueDate}</p>:null}<p className="text-sm text-text">Issued by: {snapshot.issuedBy.displayName}</p></div></section>
    <div className="overflow-x-auto"><table className="w-full min-w-[42rem] text-left text-sm"><thead className="bg-surface-muted text-muted"><tr><th className="px-5 py-3">Description</th><th className="px-5 py-3 text-right">Qty</th><th className="px-5 py-3 text-right">Unit price</th><th className="px-5 py-3 text-right">Rate</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-border">{snapshot.lines.map(line=><tr key={line.order}><td className="px-5 py-4 text-text">{line.description}</td><td className="px-5 py-4 text-right text-text">{line.quantity}</td><td className="px-5 py-4 text-right text-text">{money(snapshot.document.currency,line.unitPrice)}</td><td className="px-5 py-4 text-right text-muted">{line.customRate ? <><span className="block text-text">{formatAppliedRateLabel({ ...line.customRate, currency: snapshot.document.currency })}</span><span className="block">{money(snapshot.document.currency,line.customRate.amount)}</span></> : "—"}</td><td className="px-5 py-4 text-right font-semibold text-text">{money(snapshot.document.currency,line.total)}</td></tr>)}</tbody></table></div>
    <section className="grid gap-6 border-t border-border p-5 sm:grid-cols-[1fr_22rem] sm:p-7"><div>{snapshot.document.notes?<><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Notes</h3><p className="mt-2 whitespace-pre-wrap text-sm text-text">{snapshot.document.notes}</p></>:null}</div><dl className="grid gap-2 text-sm"><div className="flex justify-between gap-4"><dt>Subtotal</dt><dd>{money(snapshot.document.currency,snapshot.totals.subtotal)}</dd></div>{appliedRates.map(rate=><div className="flex justify-between gap-4" key={rate.key}><dt>{rate.label}</dt><dd>{money(snapshot.document.currency,rate.amount)}</dd></div>)}{snapshot.tax?<div className="flex justify-between gap-4 font-semibold"><dt>Taxable value</dt><dd>{money(snapshot.document.currency,snapshot.totals.taxableValue)}</dd></div>:null}<div className="mt-2 flex justify-between gap-4 border-t border-border pt-3 text-lg font-bold"><dt>Grand total</dt><dd>{money(snapshot.document.currency,snapshot.totals.grandTotal)}</dd></div></dl></section>
    <section className="border-t border-border p-5 sm:p-7" aria-labelledby="verification-title"><h3 id="verification-title" className="text-xs font-bold uppercase tracking-wide text-muted">CIV verification</h3>{verificationCode?<div className="mt-4 grid gap-4"><VerificationBarcode code={verificationCode}/><div><p className="font-mono text-base font-bold tracking-wide text-text">Verification Code: {verificationCode}</p><p className="mt-1 text-sm text-muted">This is a CIV-native document identity and does not imply GRA or government certification.</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-lg border border-civ-blue px-4 py-3 text-sm font-semibold text-link hover:bg-hover" href={`/verify?code=${encodeURIComponent(verificationCode)}`}>Verify this document</Link></div></div>:<p className="mt-3 text-sm text-muted">Verification code unavailable for this historical document.</p>}</section>
  </article>;
}
