import Link from "next/link";

import { VerificationBarcode } from "@/components/ui/verification-barcode";
import { buildSnapshotAppliedRateRows, formatAppliedRateLabel } from "@/features/documents/applied-rates";
import type { IssuedDocumentSnapshot } from "@/features/documents/snapshots";

const money = (currency: string, value: string) => `${currency} ${value}`;

export function IssuedDocumentView({ snapshot }: { snapshot: IssuedDocumentSnapshot }) {
  const appliedRates = buildSnapshotAppliedRateRows(snapshot);
  const verificationCode = snapshot.verification?.code ?? null;
  return <article className="mt-8 overflow-hidden border border-border bg-surface">
    {snapshot.document.isTestDocument ? <div className="border-b-2 border-danger bg-danger px-5 py-4 text-center text-lg font-black tracking-wide text-white">TEST DOCUMENT — NOT VALID</div> : null}
    <header className="border-b border-border p-5 sm:p-7"><div className="flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-civ-blue">{snapshot.document.type.replaceAll("_", " ")}</p><h2 className="mt-2 text-2xl font-bold text-text">{snapshot.document.documentNumber}</h2><p className="mt-1 text-sm text-muted">Issued {new Date(snapshot.document.issuedAt).toLocaleString("en-GH")}</p></div><div className="text-right"><p className="font-bold text-text">{snapshot.issuer.legalName ?? snapshot.issuer.displayName}</p>{snapshot.issuer.tradingName?<p className="text-sm text-muted">Trading as {snapshot.issuer.tradingName}</p>:null}<p className="mt-1 text-sm text-muted">{snapshot.issuer.address || snapshot.issuer.country}</p>{snapshot.issuer.taxpayerId?<p className="text-sm text-muted">{snapshot.issuer.taxpayerIdType === "GHANA_CARD_PIN" ? "Ghana Card PIN" : "GRA TIN"}: {snapshot.issuer.taxpayerId}</p>:null}{snapshot.issuer.vatRegistrationStatus?<p className="text-sm text-muted">VAT: {snapshot.issuer.vatRegistrationStatus.replaceAll("_", " ")}</p>:null}</div></div></header>
    {snapshot.document.adjustment?<div className="border-b border-border bg-active px-5 py-4 text-sm text-text"><strong>{snapshot.document.adjustment.direction === "REDUCE" ? "Credit against" : "Debit against"} {snapshot.document.adjustment.originalDocumentNumber}</strong> · original issue date {snapshot.document.adjustment.originalIssueDate}<span className="block mt-1">Reason: {snapshot.document.adjustment.reason}</span></div>:null}
    <section className="grid gap-5 border-b border-border p-5 sm:grid-cols-2 sm:p-7"><div><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Customer</h3><p className="mt-2 font-semibold text-text">{snapshot.customer?.name ?? "Walk-in customer"}</p>{snapshot.customer?.address?<p className="mt-1 text-sm text-muted">{snapshot.customer.address}</p>:null}{snapshot.customer?.taxpayerId?<p className="text-sm text-muted">{snapshot.customer.taxpayerIdType === "GHANA_CARD_PIN" ? "Ghana Card PIN" : "GRA TIN"}: {snapshot.customer.taxpayerId}</p>:null}</div><div className="sm:text-right"><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Record</h3><p className="mt-2 text-sm text-text">Issue date: {snapshot.document.issueDate}</p>{snapshot.document.supplyDate?<p className="text-sm text-text">Supply date: {snapshot.document.supplyDate}</p>:null}{snapshot.document.dueDate?<p className="text-sm text-text">Due date: {snapshot.document.dueDate}</p>:null}<p className="text-sm text-text">Transaction: {snapshot.document.transactionType.replaceAll("_", " ")}</p><p className="text-sm text-text">Prices: {snapshot.document.priceMode === "TAX_INCLUSIVE" ? "Tax inclusive" : "Tax exclusive"}</p><p className="text-sm text-text">Issued by: {snapshot.issuedBy.displayName}</p></div></section>
    <div className="overflow-x-auto"><table className="w-full min-w-[50rem] text-left text-sm"><thead className="bg-surface-muted text-muted"><tr><th className="px-5 py-3">Description / treatment</th><th className="px-5 py-3 text-right">Qty / unit</th><th className="px-5 py-3 text-right">Unit price</th><th className="px-5 py-3 text-right">Discount</th><th className="px-5 py-3 text-right">Tax</th><th className="px-5 py-3 text-right">Total</th></tr></thead><tbody className="divide-y divide-border">{snapshot.lines.map(line=><tr key={line.order}><td className="px-5 py-4 text-text"><span className="font-medium">{line.description}</span><span className="mt-1 block text-xs text-muted">{line.relief ? `Relieved · ${line.relief.reason} · ${line.relief.reference}` : line.taxTreatment.replaceAll("_", " ")}{line.taxTreatmentReason ? ` · ${line.taxTreatmentReason}` : ""}{line.taxTreatmentReference ? ` · ${line.taxTreatmentReference}` : ""}</span>{line.customRate?<span className="mt-1 block text-xs text-muted">{formatAppliedRateLabel({ ...line.customRate, currency: snapshot.document.currency })}: {money(snapshot.document.currency,line.customRate.amount)}</span>:null}</td><td className="px-5 py-4 text-right text-text">{line.quantity}{line.unitOfMeasure?<span className="block text-xs text-muted">{line.unitOfMeasure}</span>:null}</td><td className="px-5 py-4 text-right text-text">{money(snapshot.document.currency,line.unitPrice)}</td><td className="px-5 py-4 text-right text-text">{money(snapshot.document.currency,line.discount)}</td><td className="px-5 py-4 text-right text-text">{money(snapshot.document.currency,line.tax?.amount??"0.00")}</td><td className="px-5 py-4 text-right font-semibold text-text">{money(snapshot.document.currency,line.total)}</td></tr>)}</tbody></table></div>
    <section className="grid gap-6 border-t border-border p-5 sm:grid-cols-[1fr_22rem] sm:p-7"><div>{snapshot.document.notes?<><h3 className="text-xs font-bold uppercase tracking-wide text-muted">Notes</h3><p className="mt-2 whitespace-pre-wrap text-sm text-text">{snapshot.document.notes}</p></>:null}</div><dl className="grid gap-2 text-sm">{snapshot.totals.discount!=="0.00"?<><div className="flex justify-between gap-4"><dt>Original amount</dt><dd>{money(snapshot.document.currency,snapshot.totals.originalAmount)}</dd></div><div className="flex justify-between gap-4"><dt>Discount</dt><dd>{money(snapshot.document.currency,snapshot.totals.discount)}</dd></div></>:null}<div className="flex justify-between gap-4"><dt>Post-discount base</dt><dd>{money(snapshot.document.currency,snapshot.totals.subtotal)}</dd></div>{[["Standard-rated value",snapshot.totals.standardRatedValue],["Zero-rated value",snapshot.totals.zeroRatedValue],["Exempt value",snapshot.totals.exemptValue],["Relieved value",snapshot.totals.relievedValue]].filter(([,value])=>value!=="0.00").map(([label,value])=><div className="flex justify-between gap-4" key={label}><dt>{label}</dt><dd>{money(snapshot.document.currency,value!)}</dd></div>)}{appliedRates.map(rate=><div className="flex justify-between gap-4" key={rate.key}><dt>{rate.label}</dt><dd>{money(snapshot.document.currency,rate.amount)}</dd></div>)}{snapshot.totals.trustedTax!=="0.00"?<div className="flex justify-between gap-4 font-semibold"><dt>Total statutory tax</dt><dd>{money(snapshot.document.currency,snapshot.totals.trustedTax)}</dd></div>:null}<div className="mt-2 flex justify-between gap-4 border-t border-border pt-3 text-lg font-bold"><dt>Gross total</dt><dd>{money(snapshot.document.currency,snapshot.totals.grandTotal)}</dd></div>{snapshot.totals.withholding?<><div className="flex justify-between gap-4"><dt>VAT withholding credit</dt><dd>{money(snapshot.document.currency,snapshot.totals.withholding.amount)}</dd></div><div className="flex justify-between gap-4 font-bold"><dt>Net payable / settled</dt><dd>{money(snapshot.document.currency,snapshot.totals.netPayable??snapshot.totals.grandTotal)}</dd></div><p className="text-xs text-muted">Reference: {snapshot.totals.withholding.reference}{snapshot.totals.withholding.date ? ` · ${snapshot.totals.withholding.date}` : ""}</p></>:null}</dl></section>
    <section className="border-t border-border p-5 sm:p-7" aria-labelledby="verification-title"><h3 id="verification-title" className="text-xs font-bold uppercase tracking-wide text-muted">CIV verification</h3>{verificationCode?<div className="mt-4 grid gap-4"><VerificationBarcode code={verificationCode}/><div><p className="font-mono text-base font-bold tracking-wide text-text">Verification Code: {verificationCode}</p><p className="mt-1 text-sm text-muted">This is a CIV-native document identity and does not imply GRA or government certification.</p><Link className="mt-3 inline-flex min-h-11 items-center rounded-lg border border-civ-blue px-4 py-3 text-sm font-semibold text-link hover:bg-hover" href={`/verify?code=${encodeURIComponent(verificationCode)}`}>Verify this document</Link></div></div>:<p className="mt-3 text-sm text-muted">Verification code unavailable for this historical document.</p>}</section>
  </article>;
}
